# Generated by Django 5.0 on 2023-12-10 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionquiz',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionquiz',
            name='pub_date',
            field=models.DateField(verbose_name='date of publication'),
        ),
    ]
