# Generated by Django 5.0 on 2023-12-11 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_questionquiz_subject_alter_questionquiz_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choicequiz',
            name='update_at',
        ),
        migrations.AddField(
            model_name='questionquiz',
            name='choiceform_txt',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
