# Generated by Django 5.0 on 2023-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_remove_choicequiz_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionquiz',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
