# Generated by Django 5.0 on 2023-12-11 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_questionquiz_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionquiz',
            name='choiceform_txt',
        ),
        migrations.AddField(
            model_name='questionquiz',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
