# Generated by Django 5.0 on 2023-12-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_remove_questionquiz_choiceform_txt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionquiz',
            name='pub_date',
        ),
    ]
