# Generated by Django 5.0 on 2023-12-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_remove_questionquiz_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequiz',
            old_name='vote',
            new_name='votes',
        ),
    ]
